<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
import { useAuthStore } from '../stores/auth'

type Row = Record<string, any>
const auth=useAuthStore()
const role=auth.user?.role || 'STUDENT'
const roleNames:Record<string,string>={ADMIN:'管理员',TEACHER:'教师',STUDENT:'学生'}
const menus:Record<string,{key:string,label:string}[]>={
  ADMIN:[{key:'overview',label:'工作台'},{key:'users',label:'用户与教师'},{key:'courses',label:'课程管理'},{key:'classes',label:'班级管理'},{key:'classrooms',label:'教室管理'},{key:'schedules',label:'课次排程'},{key:'orders',label:'报名订单'}],
  TEACHER:[{key:'overview',label:'工作台'},{key:'classes',label:'我的班级'},{key:'students',label:'班级学生'},{key:'schedules',label:'我的课表'},{key:'attendance',label:'考勤登记'},{key:'assignments',label:'作业管理'},{key:'submissions',label:'作业批改'},{key:'questions',label:'题库管理'},{key:'exams',label:'考试管理'},{key:'results',label:'考试成绩'}],
  STUDENT:[{key:'overview',label:'学习概览'},{key:'courses',label:'课程与报名'},{key:'myClasses',label:'我的班级'},{key:'orders',label:'我的订单'},{key:'schedules',label:'我的课表'},{key:'attendance',label:'我的考勤'},{key:'assignments',label:'我的作业'},{key:'exams',label:'我的考试'},{key:'notifications',label:'站内通知'}],
}
const activeView=ref('overview')
const loading=ref(false)
const rows=ref<Row[]>([])
const courses=ref<Row[]>([]),classes=ref<Row[]>([]),rooms=ref<Row[]>([]),teachers=ref<Row[]>([]),schedules=ref<Row[]>([]),members=ref<Row[]>([]),openClasses=ref<Row[]>([])
const selectedClassId=ref<number|undefined>(),selectedScheduleId=ref<number|undefined>(),selectedAssignmentId=ref<number|undefined>(),selectedExamId=ref<number|undefined>(),selectedCourseId=ref<number|undefined>()
const selectedCourse=ref<Row|null>(null)
const attendanceRoster=ref<Row[]>([])
const assignmentRoster=ref<Row[]>([])
const examStart=ref<Row|null>(null)
const answers=reactive<Record<number,any>>({})
const notificationUnread=ref(0)
const classEditVisible=ref(false),roomEditVisible=ref(false),assignmentEditVisible=ref(false),questionEditVisible=ref(false)
const scheduleEditId=ref<number|undefined>(),pendingExamAnswers=ref<Row[]>([])
const classEditForm=reactive({id:0,courseId:0,teacherId:0,name:'',capacity:1,startDate:'',endDate:''})
const roomEditForm=reactive({id:0,name:'',capacity:1})
const assignmentEditForm=reactive({id:0,classId:0,title:'',content:'',deadline:''})
const questionEditForm=reactive({id:0,courseId:0,type:'SINGLE_CHOICE',content:'',optionsJson:'',answerJson:'',difficulty:'EASY'})
const courseForm=reactive({name:'',description:'',price:0})
const teacherForm=reactive({username:'',password:'',realName:''})
const classForm=reactive({courseId:undefined as number|undefined,teacherId:undefined as number|undefined,name:'',capacity:30,startDate:'',endDate:''})
const roomForm=reactive({name:'',capacity:30})
const scheduleForm=reactive({classId:undefined as number|undefined,classroomId:undefined as number|undefined,startTime:'',endTime:''})
const assignmentForm=reactive({classId:undefined as number|undefined,title:'',content:'',deadline:''})
const submissionForm=reactive({assignmentId:undefined as number|undefined,content:''})
const gradeForm=reactive({submissionId:undefined as number|undefined,score:90,feedback:''})
const questionForm=reactive({courseId:undefined as number|undefined,type:'SINGLE_CHOICE',content:'',optionsJson:'[{"id":"A","text":"选项 A"},{"id":"B","text":"选项 B"}]',answerJson:'"A"',difficulty:'EASY'})
const examForm=reactive({classId:undefined as number|undefined,title:'阶段测验',startTime:'',endTime:'',durationMinutes:60})
const ruleForm=reactive({type:'SINGLE_CHOICE',difficulty:'EASY',count:5,score:10})
const examAnswerForm=reactive({answerId:undefined as number|undefined,score:0,feedback:''})
const activeMenu=computed(()=>menus[role].find(m=>m.key===activeView.value)?.label||'工作台')
const displayName=computed(()=>auth.user?.realName||auth.user?.username||'用户')
const columns=computed(()=>{
  const configs:Record<string,[string,string][]>={
    users:[['id','ID'],['username','用户名'],['realName','姓名'],['role','角色'],['status','状态']],courses:[['id','ID'],['name','课程名称'],['price','价格'],['status','状态'],['createdAt','创建时间']],
    classes:[['id','ID'],['name','班级名称'],['courseId','课程 ID'],['teacherId','教师 ID'],['capacity','容量'],['reservedCount','预占'],['enrolledCount','已报名'],['startDate','开课日期'],['status','状态']],
    classrooms:[['id','ID'],['name','教室'],['capacity','容量'],['status','状态']],schedules:[['id','课次 ID'],['classId','班级'],['teacherId','教师'],['classroomId','教室'],['startTime','开始'],['endTime','结束'],['status','状态']],
    orders:[['id','订单 ID'],['orderNo','订单号'],['studentId','学生'],['classId','班级'],['amount','金额'],['status','状态'],['expireAt','截止时间']],
    students:[['studentId','学生 ID'],['username','用户名'],['realName','姓名'],['enrolledAt','入班时间']],attendance:[['studentId','学生 ID'],['realName','学生'],['status','考勤'],['checkedAt','登记时间']],
    assignments:[['id','作业 ID'],['title','标题'],['classId','班级'],['deadline','截止时间'],['status','状态']],submissions:[['studentId','学生'],['studentName','姓名'],['status','提交状态'],['content','提交内容'],['score','分数'],['feedback','评语'],['submittedAt','提交时间']],
    questions:[['id','题目 ID'],['courseId','课程'],['type','题型'],['content','题目'],['difficulty','难度'],['status','状态']],exams:[['id','考试 ID'],['title','考试'],['classId','班级'],['startTime','开始时间'],['endTime','结束时间'],['durationMinutes','时长'],['status','状态'],['questionCount','题数']],
    results:[['attemptId','答卷 ID'],['studentId','学生'],['studentName','姓名'],['status','状态'],['score','成绩'],['submittedAt','提交时间']],coursesStudent:[['id','课程 ID'],['name','课程'],['description','课程说明'],['price','价格'],['status','状态']],
    myClasses:[['classId','班级 ID'],['courseName','课程'],['className','班级'],['teacherId','教师'],['startDate','开始日期'],['endDate','结束日期']],notifications:[['id','通知 ID'],['title','标题'],['content','内容'],['createdAt','收到时间'],['readAt','已读时间']],
    studentAssignments:[['id','作业 ID'],['className','班级'],['title','标题'],['deadline','截止时间'],['submissionStatus','提交状态'],['score','分数'],['feedback','评语']],
    studentExams:[['id','考试 ID'],['className','班级'],['title','考试'],['startTime','开始'],['endTime','结束'],['durationMinutes','时长'],['status','状态']],studentOrders:[['id','订单 ID'],['orderNo','订单号'],['classId','班级'],['amount','金额'],['status','状态'],['expireAt','截止时间']],studentAttendance:[['className','班级'],['studentName','学生'],['status','考勤'],['checkedAt','登记时间']],
  }
  const key=activeView.value==='courses'&&role==='STUDENT'?'coursesStudent':activeView.value==='assignments'&&role==='STUDENT'?'studentAssignments':activeView.value==='exams'&&role==='STUDENT'?'studentExams':activeView.value==='orders'&&role==='STUDENT'?'studentOrders':activeView.value==='attendance'&&role==='STUDENT'?'studentAttendance':activeView.value
  return (configs[key]||[]).map(([prop,label])=>({prop,label}))
})
const dashboardStats=computed(()=>[
  {label:role==='ADMIN'?'课程总数':role==='TEACHER'?'负责班级':'已加入班级',value:role==='ADMIN'?courses.value.length:role==='TEACHER'?classes.value.length:rows.value.length},
  {label:role==='ADMIN'?'班级总数':role==='TEACHER'?'待处理事项':'待处理订单',value:role==='ADMIN'?classes.value.length:role==='TEACHER'?assignmentRoster.value.filter(x=>!x.status).length:rows.value.filter(x=>x.status==='PENDING').length},
  {label:role==='ADMIN'?'报名订单':role==='TEACHER'?'站内消息':'未读通知',value:role==='ADMIN'?rows.value.length:role==='TEACHER'?0:notificationUnread.value},
])

function list(data:any):Row[]{if(Array.isArray(data))return data;if(Array.isArray(data?.records))return data.records;if(Array.isArray(data?.records?.records))return data.records.records;return []}
function toUtc(value:string){return value?new Date(value).toISOString().slice(0,19):''}
function toLocal(value:string){if(!value)return '';const d=new Date(value.endsWith('Z')?value:`${value}Z`);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function formatTime(value:any){if(!value)return '—';return String(value).replace('T',' ').replace(/\.\d+$/,'')}
function err(){/* API client shows the server message. */}
async function loadView(){
  loading.value=true;rows.value=[]
  try{
    if(role==='ADMIN'){
      if(activeView.value==='overview'){
        const [c,k,o]=await Promise.all([api.get('/admin/courses',{page:1,size:100}),api.get('/admin/classes',{page:1,size:100}),api.get('/admin/orders',{page:1,size:100})]);courses.value=list(c);classes.value=list(k);rows.value=list(o)
      }else if(activeView.value==='users'){rows.value=list(await api.get('/admin/users',{page:1,size:100}))}
      else if(activeView.value==='courses'){courses.value=list(await api.get('/admin/courses',{page:1,size:100}));rows.value=courses.value}
      else if(activeView.value==='classes'){const [k,c,u]=await Promise.all([api.get('/admin/classes',{page:1,size:100}),api.get('/admin/courses',{page:1,size:100}),api.get('/admin/users',{page:1,size:100})]);classes.value=list(k);courses.value=list(c);rows.value=classes.value;teachers.value=list(u).filter((x:Row)=>x.role==='TEACHER')}
      else if(activeView.value==='classrooms'){rooms.value=list(await api.get('/admin/classrooms'));rows.value=rooms.value}
      else if(activeView.value==='schedules'){classes.value=list(await api.get('/admin/classes',{page:1,size:100}));rooms.value=list(await api.get('/admin/classrooms'));const id=selectedClassId.value||classes.value[0]?.id;if(id){selectedClassId.value=id;rows.value=list(await api.get(`/classes/${id}/schedules`))}}
      else if(activeView.value==='orders'){rows.value=list(await api.get('/admin/orders',{page:1,size:100}))}
    }else if(role==='TEACHER'){
      if(activeView.value==='overview'||activeView.value==='classes'){classes.value=list(await api.get('/teacher/classes'));rows.value=classes.value}
      else if(activeView.value==='students'){classes.value=list(await api.get('/teacher/classes'));const id=selectedClassId.value||classes.value[0]?.id;if(id){selectedClassId.value=id;rows.value=list(await api.get(`/teacher/classes/${id}/students`))}}
      else if(activeView.value==='schedules'){rows.value=list(await api.get('/teacher/schedules'));schedules.value=rows.value}
      else if(activeView.value==='attendance'){schedules.value=list(await api.get('/teacher/schedules'));const id=selectedScheduleId.value;if(id)attendanceRoster.value=list(await api.get(`/teacher/schedules/${id}/attendance`));rows.value=attendanceRoster.value}
      else if(activeView.value==='assignments'){classes.value=list(await api.get('/teacher/classes'));const id=selectedClassId.value||classes.value[0]?.id;if(id){selectedClassId.value=id;rows.value=list(await api.get(`/teacher/classes/${id}/assignments`))}}
      else if(activeView.value==='submissions'){const id=selectedAssignmentId.value;if(id){rows.value=list(await api.get(`/teacher/assignments/${id}/submissions`));assignmentRoster.value=rows.value}}
      else if(activeView.value==='questions'){classes.value=list(await api.get('/teacher/classes'));const id=selectedCourseId.value||classes.value[0]?.courseId;if(id)selectedCourseId.value=id;rows.value=list(await api.get('/teacher/questions',id?{courseId:id}:undefined))}
      else if(activeView.value==='exams'){classes.value=list(await api.get('/teacher/classes'));rows.value=list(await api.get('/teacher/exams',selectedClassId.value?{classId:selectedClassId.value}:undefined))}
      else if(activeView.value==='results'){rows.value=selectedExamId.value?list(await api.get(`/teacher/exams/${selectedExamId.value}/results`)):[]}
    }else{
      if(activeView.value==='overview'||activeView.value==='courses'){rows.value=list(await api.get('/courses',{page:1,size:100}));courses.value=rows.value}
      else if(activeView.value==='myClasses'){rows.value=list(await api.get('/students/me/classes'))}
      else if(activeView.value==='orders'){rows.value=list(await api.get('/orders',{page:1,size:100}))}
      else if(activeView.value==='schedules'){const my=list(await api.get('/students/me/classes'));const all=await Promise.all(my.map((x:Row)=>api.get(`/classes/${x.classId}/schedules`)));rows.value=all.flatMap(list)}
      else if(activeView.value==='attendance'){rows.value=list(await api.get('/students/me/attendance'))}
      else if(activeView.value==='assignments'){rows.value=list(await api.get('/students/me/assignments'))}
      else if(activeView.value==='exams'){rows.value=list(await api.get('/students/me/exams'))}
      else if(activeView.value==='notifications'){rows.value=list(await api.get('/notifications'));notificationUnread.value=await api.get('/notifications/unread-count')}
    }
  }catch{err()}finally{loading.value=false}
}
watch(activeView,loadView)
onMounted(loadView)

async function addCourse(){await api.post('/admin/courses',courseForm);Object.assign(courseForm,{name:'',description:'',price:0});ElMessage.success('课程已创建');await loadView()}
async function editCourse(row:Row){const {value}=await ElMessageBox.prompt('更新课程名称','修改课程',{inputValue:row.name});await api.put(`/admin/courses/${row.id}`,{name:value,description:row.description,price:row.price});await loadView()}
async function courseStatus(row:Row){const next=row.status==='PUBLISHED'?'OFFLINE':'PUBLISHED';await api.patch(`/admin/courses/${row.id}/status`,{status:next});ElMessage.success(`课程已${next==='PUBLISHED'?'上架':'下架'}`);await loadView()}
async function addTeacher(){await api.post('/admin/teachers',teacherForm);Object.assign(teacherForm,{username:'',password:'',realName:''});ElMessage.success('教师账号已创建');await loadView()}
async function toggleUser(row:Row){const status=row.status==='ACTIVE'?'DISABLED':'ACTIVE';await api.patch(`/admin/users/${row.id}/status`,{status});await loadView()}
async function addClass(){await api.post('/admin/classes',classForm);Object.assign(classForm,{courseId:undefined,teacherId:undefined,name:'',capacity:30,startDate:'',endDate:''});ElMessage.success('班级已创建');await loadView()}
async function classStatus(row:Row){const next:Record<string,string>={DRAFT:'ENROLLING',ENROLLING:'IN_PROGRESS',IN_PROGRESS:'FINISHED'};const status=next[row.status];if(!status){ElMessage.info('当前状态没有可直接执行的流转');return}await api.patch(`/admin/classes/${row.id}/status`,{status});await loadView()}
async function cancelClass(row:Row){await ElMessageBox.confirm('取消后班级不能重新开放报名，确定继续？','取消班级');await api.patch(`/admin/classes/${row.id}/status`,{status:'CANCELLED'});await loadView()}
function openClassEdit(row:Row){Object.assign(classEditForm,{id:row.id,courseId:row.courseId,teacherId:row.teacherId,name:row.name,capacity:row.capacity,startDate:row.startDate,endDate:row.endDate});classEditVisible.value=true}
async function saveClassEdit(){await api.put(`/admin/classes/${classEditForm.id}`,{courseId:classEditForm.courseId,teacherId:classEditForm.teacherId,name:classEditForm.name,capacity:classEditForm.capacity,startDate:classEditForm.startDate,endDate:classEditForm.endDate});classEditVisible.value=false;ElMessage.success('班级已更新');await loadView()}
async function addRoom(){await api.post('/admin/classrooms',roomForm);Object.assign(roomForm,{name:'',capacity:30});await loadView()}
function openRoomEdit(row:Row){Object.assign(roomEditForm,{id:row.id,name:row.name,capacity:row.capacity});roomEditVisible.value=true}
async function saveRoomEdit(){await api.put(`/admin/classrooms/${roomEditForm.id}`,{name:roomEditForm.name,capacity:roomEditForm.capacity});roomEditVisible.value=false;await loadView()}
async function toggleRoom(row:Row){await api.patch(`/admin/classrooms/${row.id}/status`,{status:row.status==='ACTIVE'?'DISABLED':'ACTIVE'});await loadView()}
function editSchedule(row:Row){scheduleEditId.value=row.id;Object.assign(scheduleForm,{classId:row.classId,classroomId:row.classroomId,startTime:toLocal(row.startTime),endTime:toLocal(row.endTime)});selectedClassId.value=row.classId}
async function addSchedule(){const body={classId:scheduleForm.classId,classroomId:scheduleForm.classroomId,startTime:toUtc(scheduleForm.startTime),endTime:toUtc(scheduleForm.endTime)};if(scheduleEditId.value)await api.put(`/admin/schedules/${scheduleEditId.value}`,body);else await api.post('/admin/schedules',body);scheduleEditId.value=undefined;ElMessage.success('课次已保存');if(scheduleForm.classId)selectedClassId.value=scheduleForm.classId;await loadView()}
async function loadClassesForCourse(){openClasses.value=selectedCourse.value?list(await api.get('/classes',{courseId:selectedCourse.value.id})):[]}
async function enroll(classId:number){const order=await api.post<Row>('/enrollments/orders',{classId});await loadView();ElMessageBox.confirm(`订单 ${order.orderNo} 已创建，金额 ¥${order.amount}。现在进行模拟支付？`,'报名订单',{confirmButtonText:'模拟支付',cancelButtonText:'稍后支付'}).then(async()=>{await api.post(`/orders/${order.id}/pay`);ElMessage.success('模拟支付成功，已加入班级');await loadView()}).catch(()=>{})}
async function pay(row:Row){await api.post(`/orders/${row.id}/pay`);ElMessage.success('支付成功');await loadView()}
async function cancelOrder(row:Row){await api.post(`/orders/${row.id}/cancel`);await loadView()}
async function selectTeacherClass(row:Row){selectedClassId.value=row.id;activeView.value='students';await loadView()}
async function useSchedule(row:Row){selectedScheduleId.value=row.id;activeView.value='attendance';await loadView()}
async function loadAttendance(){if(!selectedScheduleId.value)return;attendanceRoster.value=list(await api.get(`/teacher/schedules/${selectedScheduleId.value}/attendance`)).map((x:Row)=>({...x,editStatus:x.status||'PRESENT'}));rows.value=attendanceRoster.value}
async function saveAttendance(){if(!selectedScheduleId.value)return;const records=attendanceRoster.value.filter(x=>x.editStatus).map(x=>({studentId:x.studentId,status:x.editStatus}));if(!records.length){ElMessage.warning('请至少选择一名学生');return}await api.post(`/teacher/schedules/${selectedScheduleId.value}/attendance`,{records});ElMessage.success('考勤已保存');await loadAttendance()}
async function addAssignment(){await api.post('/teacher/assignments', {classId:assignmentForm.classId,title:assignmentForm.title,content:assignmentForm.content,deadline:toUtc(assignmentForm.deadline)});ElMessage.success('作业草稿已创建');Object.assign(assignmentForm,{title:'',content:'',deadline:''});selectedClassId.value=assignmentForm.classId;await loadView()}
async function assignmentAction(row:Row,action:string){if(action==='progress'){selectedAssignmentId.value=row.id;activeView.value='submissions';return}await api.post(`/teacher/assignments/${row.id}/${action}`);await loadView()}
function editAssignment(row:Row){Object.assign(assignmentEditForm,{id:row.id,classId:row.classId,title:row.title,content:row.content,deadline:toLocal(row.deadline)});assignmentEditVisible.value=true}
async function saveAssignmentEdit(){await api.put(`/teacher/assignments/${assignmentEditForm.id}`,{classId:assignmentEditForm.classId,title:assignmentEditForm.title,content:assignmentEditForm.content,deadline:toUtc(assignmentEditForm.deadline)});assignmentEditVisible.value=false;await loadView()}
async function submitAssignment(row:Row){submissionForm.assignmentId=row.id;submissionForm.content=row.submissionContent||'';await ElMessageBox.prompt('输入作业内容','提交作业',{inputValue:submissionForm.content,inputType:'textarea',inputValidator:v=>Boolean(v?.trim())||'内容不能为空'}).then(async({value})=>{await api.put(`/assignments/${row.id}/submission`,{content:value});ElMessage.success('提交已保存');await loadView()})}
async function gradeSubmission(row:Row){gradeForm.submissionId=row.id;await ElMessageBox.prompt('输入 0–100 分','批改作业',{inputValue:String(row.score??90),inputValidator:v=>Number(v)>=0&&Number(v)<=100||'分数应在 0 到 100 之间'}).then(async({value})=>{const feedback=window.prompt('评语（可留空）',row.feedback||'')||'';await api.post(`/teacher/submissions/${row.id}/grade`,{score:Number(value),feedback});ElMessage.success('批改已保存');await loadView()})}
async function addQuestion(){await api.post('/teacher/questions',{...questionForm});ElMessage.success('题目已添加');questionForm.content='';await loadView()}
async function questionStatus(row:Row){await api.patch(`/teacher/questions/${row.id}/status`,{status:row.status==='ACTIVE'?'INACTIVE':'ACTIVE'});await loadView()}
function editQuestion(row:Row){Object.assign(questionEditForm,{id:row.id,courseId:row.courseId,type:row.type,content:row.content,optionsJson:row.optionsJson||'',answerJson:row.answerJson,difficulty:row.difficulty});questionEditVisible.value=true}
async function saveQuestionEdit(){await api.put(`/teacher/questions/${questionEditForm.id}`,{courseId:questionEditForm.courseId,type:questionEditForm.type,content:questionEditForm.content,optionsJson:questionEditForm.optionsJson||null,answerJson:questionEditForm.answerJson,difficulty:questionEditForm.difficulty});questionEditVisible.value=false;await loadView()}
async function addExam(){const exam=await api.post<Row>('/teacher/exams',{...examForm,startTime:toUtc(examForm.startTime),endTime:toUtc(examForm.endTime)});selectedExamId.value=exam.id;selectedClassId.value=exam.classId;ElMessage.success(`考试草稿已创建（ID ${exam.id}）`);await loadView()}
async function generateExam(row?:Row){const id=row?.id||selectedExamId.value;if(!id)return;await api.post(`/teacher/exams/${id}/generate`,{rules:[{...ruleForm,count:Number(ruleForm.count),score:Number(ruleForm.score)}]});ElMessage.success('组卷完成');selectedExamId.value=id;await loadView()}
async function examAction(row:Row,action:string){selectedExamId.value=row.id;if(action==='results'){activeView.value='results';return}await api.post(`/teacher/exams/${row.id}/${action}`);await loadView()}
async function loadResults(){rows.value=selectedExamId.value?list(await api.get(`/teacher/exams/${selectedExamId.value}/results`)):[]}
async function loadPendingAnswers(){pendingExamAnswers.value=selectedExamId.value?list(await api.get(`/teacher/exams/${selectedExamId.value}/answers`)):[]}
async function gradeExamAnswer(row:Row){const {value}=await ElMessageBox.prompt(`学生 ${row.studentName} 的答案：${row.answerJson||'（空）'}\n题目：${row.content}\n本题满分：${row.maxScore}`,'批改简答题',{inputValue:String(row.maxScore),inputValidator:v=>Number(v)>=0&&Number(v)<=Number(row.maxScore)||`分数应在 0 到 ${row.maxScore} 之间`});const feedback=window.prompt('评语（可留空）','')||'';await api.post(`/teacher/exam-answers/${row.answerId}/grade`,{score:Number(value),feedback});ElMessage.success('主观题已批改');await loadPendingAnswers();await loadResults()}
async function startExam(row:Row){examStart.value=await api.post(`/exams/${row.id}/start`);for(const q of examStart.value?.questions||[])answers[q.id]=q.type==='MULTIPLE_CHOICE'?[]:null;ElMessage.success('考试已开始，提交截止 '+formatTime(examStart.value?.deadline))}
async function submitExam(){if(!examStart.value)return;await api.post(`/exams/${examStart.value.examId}/submit`,{answers:{...answers}});ElMessage.success('答卷已提交');examStart.value=null;await loadView()}
async function showResult(row:Row){const result=await api.get(`/exams/${row.id}/result`);ElMessageBox.alert(`考试：${result.examTitle}\n成绩：${result.score}\n状态：${result.status}`,'考试成绩',{confirmButtonText:'关闭'})}
async function markRead(row:Row){await api.patch(`/notifications/${row.id}/read`);await loadView()}
async function showClassSchedule(row:Row){selectedClassId.value=row.classId;rows.value=list(await api.get(`/classes/${row.classId}/schedules`));activeView.value='schedules'}
function logout(){auth.logout();window.location.href='/login'}

onMounted(()=>{window.addEventListener('educore:unauthorized',logout)})
</script>

<template>
  <div class="app-shell">
    <aside class="sidebar">
      <div class="sidebar-brand"><div class="brand-mark">E</div><div><strong>EduCore</strong><small>LEARNING PLATFORM</small></div></div>
      <div class="nav-label">{{ roleNames[role] }}工作空间</div>
      <nav class="side-nav">
        <button v-for="item in menus[role]" :key="item.key" class="nav-item" :class="{active:activeView===item.key}" @click="activeView=item.key"><span class="nav-dot"></span>{{ item.label }}</button>
      </nav>
      <div class="sidebar-foot"><strong>{{ displayName }}</strong>{{ roleNames[role] }} · EduCore V1.0</div>
    </aside>
    <main class="main-shell">
      <header class="topbar"><div><div class="crumb">EduCore / {{ activeMenu }}</div><h1>{{ activeMenu }}</h1></div><div class="user-area"><div class="avatar">{{ displayName.slice(0,1) }}</div><div class="user-meta"><div class="user-name">{{ displayName }}</div><div class="user-role">{{ roleNames[role] }}账号</div></div><el-button text @click="logout">退出</el-button></div></header>
      <section class="workspace">
        <div class="welcome-row"><div><h2>{{ role==='STUDENT'?'你好，'+displayName:'欢迎回来，'+displayName }}</h2><p>{{ role==='ADMIN'?'把课程、教师和教学安排放在一个工作台统一管理。':role==='TEACHER'?'查看班级进度，继续安排教学与学习反馈。':'继续你的课程和学习计划。' }}</p></div><span class="role-tag">{{ roleNames[role] }}空间</span></div>
        <div v-if="activeView==='overview'" class="metric-grid"><div v-for="metric in dashboardStats" :key="metric.label" class="metric-card"><span>{{ metric.label }}</span><strong>{{ metric.value }}</strong></div></div>

        <el-card v-if="role==='ADMIN'&&activeView==='users'" class="content-card section-gap" shadow="never">
          <template #header><div class="card-title"><div><h3>账号管理</h3><p>创建教师账号并管理用户状态</p></div></div></template>
          <el-form :model="teacherForm" inline class="filters"><el-form-item label="用户名"><el-input v-model="teacherForm.username" placeholder="teacher01" /></el-form-item><el-form-item label="姓名"><el-input v-model="teacherForm.realName" placeholder="教师姓名" /></el-form-item><el-form-item label="初始密码"><el-input v-model="teacherForm.password" type="password" show-password /></el-form-item><el-button type="primary" @click="addTeacher">创建教师</el-button></el-form>
          <el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="110" /><el-table-column label="操作" width="110"><template #default="{row}"><el-button link type="primary" @click="toggleUser(row)">{{ row.status==='ACTIVE'?'禁用':'启用' }}</el-button></template></el-table-column></el-table>
        </el-card>

        <el-card v-if="role==='ADMIN'&&activeView==='courses'" class="content-card section-gap" shadow="never">
          <template #header><div class="card-title"><div><h3>课程目录</h3><p>先创建课程并上架，再开放教学班报名</p></div></div></template>
          <el-form :model="courseForm" inline class="filters"><el-form-item label="课程名称"><el-input v-model="courseForm.name" placeholder="课程名称" /></el-form-item><el-form-item label="价格"><el-input-number v-model="courseForm.price" :min="0" :precision="2" /></el-form-item><el-form-item label="课程说明"><el-input v-model="courseForm.description" placeholder="简要描述" /></el-form-item><el-button type="primary" @click="addCourse">创建课程</el-button></el-form>
          <el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="110" /><el-table-column label="操作" width="185"><template #default="{row}"><div class="table-actions"><el-button link type="primary" @click="editCourse(row)">修改</el-button><el-button link type="primary" @click="courseStatus(row)">{{ row.status==='PUBLISHED'?'下架':'上架' }}</el-button></div></template></el-table-column></el-table>
        </el-card>

        <el-card v-if="role==='ADMIN'&&activeView==='classes'" class="content-card section-gap" shadow="never">
          <template #header><div class="card-title"><div><h3>教学班</h3><p>班级独立于课程，教师由一个主讲人负责</p></div></div></template>
          <el-form :model="classForm" inline class="filters"><el-form-item label="课程"><el-select v-model="classForm.courseId" placeholder="选择课程"><el-option v-for="c in courses" :key="c.id" :label="`${c.name} (#${c.id})`" :value="c.id" /></el-select></el-form-item><el-form-item label="主讲教师"><el-select v-model="classForm.teacherId" placeholder="选择教师"><el-option v-for="t in teachers" :key="t.id" :label="`${t.realName} (#${t.id})`" :value="t.id" /></el-select></el-form-item><el-form-item label="班级名"><el-input v-model="classForm.name" placeholder="Java 一班" /></el-form-item><el-form-item label="容量"><el-input-number v-model="classForm.capacity" :min="1" /></el-form-item><el-form-item label="开课日期"><el-date-picker v-model="classForm.startDate" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="结课日期"><el-date-picker v-model="classForm.endDate" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-button type="primary" @click="addClass">创建班级</el-button></el-form>
          <el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="105" /><el-table-column label="操作" min-width="265"><template #default="{row}"><el-button link type="primary" @click="openClassEdit(row)">修改</el-button><el-button link type="primary" @click="classStatus(row)">{{ row.status==='DRAFT'?'开放报名':row.status==='ENROLLING'?'开始教学':row.status==='IN_PROGRESS'?'结束教学':'—' }}</el-button><el-button v-if="row.status==='DRAFT'||row.status==='ENROLLING'" link type="danger" @click="cancelClass(row)">取消</el-button></template></el-table-column></el-table>
        </el-card>

        <el-card v-if="role==='ADMIN'&&activeView==='classrooms'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>教室资源</h3><p>排课时会校验教室容量和可用状态</p></div></div></template><el-form :model="roomForm" inline class="filters"><el-form-item label="教室名称"><el-input v-model="roomForm.name" /></el-form-item><el-form-item label="容量"><el-input-number v-model="roomForm.capacity" :min="1" /></el-form-item><el-button type="primary" @click="addRoom">添加教室</el-button></el-form><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" /><el-table-column label="操作" min-width="170"><template #default="{row}"><el-button link type="primary" @click="openRoomEdit(row)">修改</el-button><el-button link type="primary" @click="toggleRoom(row)">{{ row.status==='ACTIVE'?'停用':'启用' }}</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='ADMIN'&&activeView==='schedules'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>排课安排</h3><p>冲突由后端以事务锁和半开时间区间校验</p></div></div></template><el-form :model="scheduleForm" inline class="filters"><el-form-item label="班级"><el-select v-model="scheduleForm.classId" @change="selectedClassId=$event"><el-option v-for="c in classes" :key="c.id" :label="`${c.name} (#${c.id})`" :value="c.id" /></el-select></el-form-item><el-form-item label="教室"><el-select v-model="scheduleForm.classroomId"><el-option v-for="room in rooms.filter(x=>x.status==='ACTIVE')" :key="room.id" :label="`${room.name} (${room.capacity})`" :value="room.id" /></el-select></el-form-item><el-form-item label="开始"><el-date-picker v-model="scheduleForm.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm" /></el-form-item><el-form-item label="结束"><el-date-picker v-model="scheduleForm.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm" /></el-form-item><el-button type="primary" @click="addSchedule">{{ scheduleEditId?'保存修改':'创建课次' }}</el-button><el-button v-if="scheduleEditId" @click="scheduleEditId=undefined">取消修改</el-button><el-button @click="loadView">刷新课表</el-button></el-form><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130" /><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='SCHEDULED'" link type="primary" @click="editSchedule(row)">修改课次</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='ADMIN'&&activeView==='orders'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>报名订单</h3><p>订单和支付流水保持数据库事务一致</p></div></div></template><el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="120" /></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&['overview','classes','students'].includes(activeView)" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>{{ activeView==='students'?'班级学生':'我负责的班级' }}</h3><p>班级、学生名单和名额状态来自服务端</p></div><el-select v-if="activeView==='students'" v-model="selectedClassId" placeholder="选班级" @change="loadView"><el-option v-for="c in classes" :key="c.id" :label="`${c.name} (#${c.id})`" :value="c.id" /></el-select></div></template><el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in (activeView==='students'?columns:[{prop:'id',label:'班级 ID'},{prop:'name',label:'班级'},{prop:'courseId',label:'课程 ID'},{prop:'capacity',label:'容量'},{prop:'enrolledCount',label:'已报名'},{prop:'startDate',label:'开始日期'},{prop:'status',label:'状态'}])" :key="c.prop" :prop="c.prop" :label="c.label" min-width="115" /><el-table-column v-if="activeView!=='students'" label="操作"><template #default="{row}"><el-button link type="primary" @click="selectTeacherClass(row)">查看学生</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='schedules'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>授课日程</h3><p>点击课次可直接登记考勤</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130" /><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="useSchedule(row)">登记考勤</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='attendance'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>批量考勤</h3><p>重复登记会更新原记录，不会产生重复行</p></div></div></template><div class="inline-form"><el-form-item label="课次"><el-select v-model="selectedScheduleId" placeholder="选择课次"><el-option v-for="s in schedules" :key="s.id" :label="`课次 #${s.id} · 班级 ${s.classId} · ${formatTime(s.startTime)}`" :value="s.id" /></el-select></el-form-item><el-button @click="loadAttendance">读取学生名单</el-button><el-button type="primary" @click="saveAttendance">保存考勤</el-button></div><el-table class="section-gap" :data="attendanceRoster" v-loading="loading"><el-table-column prop="studentId" label="学生 ID"/><el-table-column prop="realName" label="学生姓名"/><el-table-column label="考勤状态"><template #default="{row}"><el-select v-model="row.editStatus" placeholder="选择状态"><el-option v-for="v in ['PRESENT','LATE','ABSENT','LEAVE']" :key="v" :label="v" :value="v" /></el-select></template></el-table-column><el-table-column prop="status" label="已保存状态"/></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='assignments'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>作业管理</h3><p>发布后核心内容锁定；截止时间由后端校验</p></div></div></template><el-form :model="assignmentForm" inline class="filters"><el-form-item label="班级"><el-select v-model="assignmentForm.classId"><el-option v-for="c in classes" :key="c.id" :label="`${c.name} (#${c.id})`" :value="c.id" /></el-select></el-form-item><el-form-item label="作业标题"><el-input v-model="assignmentForm.title" /></el-form-item><el-form-item label="截止时间"><el-date-picker v-model="assignmentForm.deadline" type="datetime" value-format="YYYY-MM-DDTHH:mm" /></el-form-item><el-form-item label="内容"><el-input v-model="assignmentForm.content" /></el-form-item><el-button type="primary" @click="addAssignment">创建草稿</el-button><el-button @click="loadView">刷新</el-button></el-form><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="120"/><el-table-column label="操作" width="260"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" link type="primary" @click="editAssignment(row)">编辑草稿</el-button><el-button v-if="row.status==='DRAFT'" link type="primary" @click="assignmentAction(row,'publish')">发布</el-button><el-button v-if="row.status==='PUBLISHED'" link type="warning" @click="assignmentAction(row,'close')">关闭</el-button><el-button link type="primary" @click="assignmentAction(row,'progress')">提交情况</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='submissions'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>作业提交进度</h3><p>未提交名单也会出现在班级花名册中</p></div><el-input-number v-model="selectedAssignmentId" :min="1" placeholder="作业 ID" @change="loadView" /></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="125"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='SUBMITTED'" link type="primary" @click="gradeSubmission(row)">批改</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='questions'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>课程题库</h3><p>答案只在教师题库返回；学生考试页面不读取答案</p></div></div></template><el-form :model="questionForm" class="form-grid"><el-form-item label="课程"><el-select v-model="questionForm.courseId"><el-option v-for="id in [...new Set(classes.map(c=>c.courseId))]" :key="id" :label="`课程 #${id}`" :value="id"/></el-select></el-form-item><el-form-item label="题型"><el-select v-model="questionForm.type"><el-option v-for="v in ['SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="难度"><el-select v-model="questionForm.difficulty"><el-option v-for="v in ['EASY','MEDIUM','HARD']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="题目"><el-input v-model="questionForm.content"/></el-form-item><el-form-item label="选项 JSON"><el-input v-model="questionForm.optionsJson" type="textarea" :rows="3"/></el-form-item><el-form-item label="答案 JSON"><el-input v-model="questionForm.answerJson"/></el-form-item><div class="span-2"><el-button type="primary" @click="addQuestion">添加题目</el-button><el-button @click="loadView">刷新题库</el-button></div></el-form><el-table class="section-gap" :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="120"/><el-table-column label="操作" min-width="170"><template #default="{row}"><el-button link type="primary" @click="editQuestion(row)">修改</el-button><el-button link type="primary" @click="questionStatus(row)">{{ row.status==='ACTIVE'?'停用':'启用' }}</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='exams'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>考试与组卷</h3><p>组卷规则按题型与难度抽取，并保存不可变快照</p></div></div></template><el-form :model="examForm" inline class="filters"><el-form-item label="班级"><el-select v-model="examForm.classId"><el-option v-for="c in classes" :key="c.id" :label="`${c.name} (#${c.id})`" :value="c.id"/></el-select></el-form-item><el-form-item label="标题"><el-input v-model="examForm.title"/></el-form-item><el-form-item label="开始"><el-date-picker v-model="examForm.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm"/></el-form-item><el-form-item label="结束"><el-date-picker v-model="examForm.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm"/></el-form-item><el-form-item label="分钟"><el-input-number v-model="examForm.durationMinutes" :min="1" :max="1440"/></el-form-item><el-button type="primary" @click="addExam">创建考试</el-button></el-form><el-form :model="ruleForm" inline class="filters"><el-form-item label="组卷题型"><el-select v-model="ruleForm.type"><el-option v-for="v in ['SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="难度"><el-select v-model="ruleForm.difficulty"><el-option v-for="v in ['EASY','MEDIUM','HARD']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="数量"><el-input-number v-model="ruleForm.count" :min="1"/></el-form-item><el-form-item label="单题分数"><el-input-number v-model="ruleForm.score" :min="0.01" :precision="2"/></el-form-item><el-form-item label="考试 ID"><el-input-number v-model="selectedExamId" :min="1"/></el-form-item><el-button @click="generateExam()">按规则组卷</el-button><el-button @click="loadView">刷新</el-button></el-form><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/><el-table-column label="操作" width="230"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" link type="primary" @click="generateExam(row)">组卷</el-button><el-button v-if="row.status==='DRAFT'" link type="primary" @click="examAction(row,'publish')">发布</el-button><el-button v-if="row.status==='PUBLISHED'" link type="warning" @click="examAction(row,'close')">关闭</el-button><el-button link type="primary" @click="examAction(row,'results')">成绩</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='TEACHER'&&activeView==='results'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>班级考试成绩</h3><p>主观题需要完成批改后才公布最终成绩</p></div><div class="inline-form"><el-input-number v-model="selectedExamId" :min="1" placeholder="考试 ID"/><el-button @click="loadResults">查询成绩</el-button><el-button @click="loadPendingAnswers">待批简答题</el-button></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/><el-table-column label="答题批改"><template #default="{row}"><el-tag v-if="row.status!=='GRADED'" type="warning">待完成主观题批改</el-tag><span v-else>已出分</span></template></el-table-column></el-table><div v-if="pendingExamAnswers.length" class="section-gap"><h3>待批简答题</h3><el-table :data="pendingExamAnswers"><el-table-column prop="studentName" label="学生"/><el-table-column prop="content" label="题目" min-width="200"/><el-table-column prop="answerJson" label="学生答案" min-width="200"/><el-table-column prop="maxScore" label="满分"/><el-table-column label="操作"><template #default="{row}"><el-button type="primary" link @click="gradeExamAnswer(row)">批改</el-button></template></el-table-column></el-table></div></el-card>

        <el-card v-if="role==='STUDENT'&&['overview','courses'].includes(activeView)" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>课程目录</h3><p>进入课程后查看当前开放报名的班级</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column prop="name" label="课程" min-width="150"/><el-table-column prop="description" label="课程说明" min-width="230" show-overflow-tooltip/><el-table-column prop="price" label="价格" width="100"/><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="selectedCourse=row;loadClassesForCourse()">查看开放班级</el-button></template></el-table-column></el-table><div v-if="selectedCourse" class="section-gap"><div class="card-title"><h3>{{ selectedCourse.name }} · 开放班级</h3><el-button text @click="selectedCourse=null;openClasses=[]">收起</el-button></div><el-table :data="openClasses"><el-table-column prop="id" label="班级 ID"/><el-table-column prop="name" label="班级"/><el-table-column prop="teacherId" label="教师"/><el-table-column prop="capacity" label="容量"/><el-table-column prop="enrolledCount" label="已报名"/><el-table-column prop="startDate" label="开课日期"/><el-table-column label="报名"><template #default="{row}"><el-button type="primary" size="small" @click="enroll(row.id)">报名并创建订单</el-button></template></el-table-column></el-table></div></el-card>

        <el-card v-if="role==='STUDENT'&&activeView==='myClasses'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>我的班级</h3><p>模拟支付成功后正式加入班级</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/><el-table-column label="课表"><template #default="{row}"><el-button link type="primary" @click="showClassSchedule(row)">查看课表</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='STUDENT'&&activeView==='orders'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>我的订单</h3><p>支付成功后自动正式入班；重复支付不会重复记账</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='PENDING'" link type="primary" @click="pay(row)">模拟支付</el-button><el-button v-if="row.status==='PENDING'" link type="danger" @click="cancelOrder(row)">取消</el-button></template></el-table-column></el-table></el-card>

        <el-card v-if="role==='STUDENT'&&activeView==='schedules'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>我的课表</h3><p>仅聚合本人正式加入班级的课次</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/></el-table></el-card>
        <el-card v-if="role==='STUDENT'&&activeView==='attendance'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>我的考勤</h3><p>考勤记录为只读数据</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/></el-table></el-card>
        <el-card v-if="role==='STUDENT'&&activeView==='assignments'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>我的作业</h3><p>提交后截止前可修改，教师批改后锁定</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='PUBLISHED'&&row.submissionStatus!=='GRADED'" link type="primary" @click="submitAssignment(row)">{{ row.submissionId?'修改提交':'提交作业' }}</el-button></template></el-table-column></el-table></el-card>
        <el-card v-if="role==='STUDENT'&&activeView==='exams'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>在线考试</h3><p>服务器检查开考时间、考试截止时间和答卷状态</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="130"/><el-table-column label="操作" width="170"><template #default="{row}"><el-button v-if="row.status==='PUBLISHED'" link type="primary" @click="startExam(row)">开始 / 继续</el-button><el-button link type="success" @click="showResult(row)">查看成绩</el-button></template></el-table-column></el-table><div v-if="examStart" class="exam-panel section-gap"><div class="card-title"><div><h3>答题中 · {{ examStart.questions.length }} 道题</h3><p>截止时间：{{ formatTime(examStart.deadline) }}</p></div><el-button type="primary" @click="submitExam">提交整份答卷</el-button></div><div v-for="(q,index) in examStart.questions" :key="q.id" class="exam-question"><div class="exam-question-title">{{ Number(index)+1 }}. {{ q.content }} <span class="muted-copy">（{{ q.score }} 分）</span></div><el-radio-group v-if="q.type==='SINGLE_CHOICE'||q.type==='TRUE_FALSE'" v-model="answers[q.id]" class="choice-list"><el-radio v-for="option in (typeof q.optionsJson==='string'?JSON.parse(q.optionsJson||'[]'):q.optionsJson||[])" :key="option.id||option" :value="option.id||option">{{ option.text||option }}</el-radio><el-radio v-if="q.type==='TRUE_FALSE'" :value="true">正确</el-radio><el-radio v-if="q.type==='TRUE_FALSE'" :value="false">错误</el-radio></el-radio-group><el-checkbox-group v-else-if="q.type==='MULTIPLE_CHOICE'" v-model="answers[q.id]"><el-checkbox v-for="option in (typeof q.optionsJson==='string'?JSON.parse(q.optionsJson||'[]'):q.optionsJson||[])" :key="option.id||option" :value="option.id||option">{{ option.text||option }}</el-checkbox></el-checkbox-group><el-input v-else v-model="answers[q.id]" type="textarea" :rows="4" placeholder="写下你的答案"/></div></div></el-card>
        <el-card v-if="role==='STUDENT'&&activeView==='notifications'" class="content-card section-gap" shadow="never"><template #header><div class="card-title"><div><h3>站内通知</h3><p>未读 {{ notificationUnread }} 条</p></div></div></template><el-table :data="rows" v-loading="loading"><el-table-column v-for="c in columns" :key="c.prop" :prop="c.prop" :label="c.label" min-width="150"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="!row.readAt" link type="primary" @click="markRead(row)">标为已读</el-button><el-tag v-else type="info">已读</el-tag></template></el-table-column></el-table></el-card>

        <el-card v-if="!((role==='ADMIN'&&['users','courses','classes','classrooms','schedules','orders'].includes(activeView))||(role==='TEACHER'&&['overview','classes','students','schedules','attendance','assignments','submissions','questions','exams','results'].includes(activeView))||(role==='STUDENT'&&['overview','courses','myClasses','orders','schedules','attendance','assignments','exams','notifications'].includes(activeView)))" class="content-card section-gap" shadow="never"><div class="empty-state">选择左侧功能开始使用</div></el-card>
        <el-dialog v-model="classEditVisible" title="修改班级" width="560px"><el-form :model="classEditForm" label-position="top" class="form-grid"><el-form-item label="课程"><el-select v-model="classEditForm.courseId"><el-option v-for="c in courses" :key="c.id" :label="`${c.name} (#${c.id})`" :value="c.id"/></el-select></el-form-item><el-form-item label="主讲教师"><el-select v-model="classEditForm.teacherId"><el-option v-for="t in teachers" :key="t.id" :label="`${t.realName} (#${t.id})`" :value="t.id"/></el-select></el-form-item><el-form-item label="班级名称"><el-input v-model="classEditForm.name"/></el-form-item><el-form-item label="容量"><el-input-number v-model="classEditForm.capacity" :min="1"/></el-form-item><el-form-item label="开始日期"><el-date-picker v-model="classEditForm.startDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="结束日期"><el-date-picker v-model="classEditForm.endDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="classEditVisible=false">取消</el-button><el-button type="primary" @click="saveClassEdit">保存修改</el-button></template></el-dialog>
        <el-dialog v-model="roomEditVisible" title="修改教室" width="440px"><el-form :model="roomEditForm" label-position="top"><el-form-item label="教室名称"><el-input v-model="roomEditForm.name"/></el-form-item><el-form-item label="容量"><el-input-number v-model="roomEditForm.capacity" :min="1"/></el-form-item></el-form><template #footer><el-button @click="roomEditVisible=false">取消</el-button><el-button type="primary" @click="saveRoomEdit">保存修改</el-button></template></el-dialog>
        <el-dialog v-model="assignmentEditVisible" title="修改作业草稿" width="560px"><el-form :model="assignmentEditForm" label-position="top"><el-form-item label="标题"><el-input v-model="assignmentEditForm.title"/></el-form-item><el-form-item label="截止时间"><el-date-picker v-model="assignmentEditForm.deadline" type="datetime" value-format="YYYY-MM-DDTHH:mm"/></el-form-item><el-form-item label="内容"><el-input v-model="assignmentEditForm.content" type="textarea" :rows="5"/></el-form-item></el-form><template #footer><el-button @click="assignmentEditVisible=false">取消</el-button><el-button type="primary" @click="saveAssignmentEdit">保存草稿</el-button></template></el-dialog>
        <el-dialog v-model="questionEditVisible" title="修改题目" width="620px"><el-form :model="questionEditForm" label-position="top" class="form-grid"><el-form-item label="课程"><el-select v-model="questionEditForm.courseId"><el-option v-for="id in [...new Set(classes.map(c=>c.courseId))]" :key="id" :label="`课程 #${id}`" :value="id"/></el-select></el-form-item><el-form-item label="题型"><el-select v-model="questionEditForm.type"><el-option v-for="v in ['SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="难度"><el-select v-model="questionEditForm.difficulty"><el-option v-for="v in ['EASY','MEDIUM','HARD']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="题目"><el-input v-model="questionEditForm.content"/></el-form-item><el-form-item label="选项 JSON"><el-input v-model="questionEditForm.optionsJson" type="textarea" :rows="3"/></el-form-item><el-form-item label="答案 JSON"><el-input v-model="questionEditForm.answerJson"/></el-form-item></el-form><template #footer><el-button @click="questionEditVisible=false">取消</el-button><el-button type="primary" @click="saveQuestionEdit">保存修改</el-button></template></el-dialog>
      </section>
    </main>
  </div>
</template>
