package com.educore.common;

public enum ApiErrorCode {
    SUCCESS, VALIDATION_ERROR, UNAUTHENTICATED, FORBIDDEN, USER_NOT_FOUND,
    USERNAME_TAKEN, INVALID_CREDENTIALS, USER_DISABLED, DUPLICATE_RESOURCE, INTERNAL_ERROR
}
