package com.educore.common;

public enum ApiErrorCode {
    SUCCESS, VALIDATION_ERROR, UNAUTHENTICATED, FORBIDDEN, USER_NOT_FOUND,
    USERNAME_TAKEN, INVALID_CREDENTIALS, USER_DISABLED, DUPLICATE_RESOURCE,
    COURSE_NOT_FOUND, CLASS_NOT_FOUND, CLASSROOM_NOT_FOUND, SCHEDULE_NOT_FOUND,
    INVALID_STATE, CAPACITY_EXCEEDED, SCHEDULE_CONFLICT, RESOURCE_UNAVAILABLE, INTERNAL_ERROR,
    ORDER_NOT_FOUND, ORDER_EXPIRED, ORDER_OWNER_MISMATCH, ALREADY_ENROLLED, CLASS_FULL,
    INVALID_ORDER_STATE, PAYMENT_NOT_FOUND, ATTENDANCE_NOT_FOUND, ASSIGNMENT_NOT_FOUND,
    SUBMISSION_NOT_FOUND, NOTIFICATION_NOT_FOUND, QUESTION_NOT_FOUND, EXAM_NOT_FOUND,
    EXAM_ATTEMPT_NOT_FOUND, EXAM_QUESTION_NOT_FOUND
}
