package com.educore.common;

public enum ApiErrorCode {
    SUCCESS, VALIDATION_ERROR, UNAUTHENTICATED, FORBIDDEN, USER_NOT_FOUND,
    USERNAME_TAKEN, INVALID_CREDENTIALS, USER_DISABLED, DUPLICATE_RESOURCE,
    COURSE_NOT_FOUND, CLASS_NOT_FOUND, CLASSROOM_NOT_FOUND, SCHEDULE_NOT_FOUND,
    INVALID_STATE, CAPACITY_EXCEEDED, SCHEDULE_CONFLICT, RESOURCE_UNAVAILABLE, INTERNAL_ERROR
}
